import dotenv from 'dotenv';
dotenv.config();

const { 
  PORT, 
  NODE_ENV, 
  MONGO_URI, 
  SENTRY_DSN,
  DATABASE_URL,
  JWT_ACCESS_SECRET,
  JWT_REFRESH_SECRET,
  JWT_ACCESS_EXPIRES_IN,
  JWT_REFRESH_EXPIRES_IN,
  CLIENT_URL,
  PAYSTACK_SECRET_KEY,
  PAYSTACK_PUBLIC_KEY,
  RESEND_API_KEY,
  RESEND_FROM_EMAIL,
} = process.env;

export { 
  PORT, 
  NODE_ENV, 
  MONGO_URI, 
  SENTRY_DSN,
  DATABASE_URL,
  JWT_ACCESS_SECRET,
  JWT_REFRESH_SECRET,
  JWT_ACCESS_EXPIRES_IN,
  JWT_REFRESH_EXPIRES_IN,
  CLIENT_URL,
  PAYSTACK_SECRET_KEY,
  PAYSTACK_PUBLIC_KEY,
  RESEND_API_KEY,
  RESEND_FROM_EMAIL,
};
