import dotenv from 'dotenv';
dotenv.config();

const { 
  PORT, 
  NODE_ENV, 
  MONGO_URI, 
  SENTRY_DSN,
  DATABASE_URL,
  CLERK_PUBLISHABLE_KEY,
  CLERK_SECRET_KEY,
  CLIENT_URL,
  RESEND_API_KEY,
  RESEND_FROM_EMAIL,
  R2_ACCOUNT_ID,
  R2_ACCESS_KEY_ID,
  R2_SECRET_ACCESS_KEY,
  R2_BUCKET_NAME,
  R2_PUBLIC_URL,
  PAYMENT_WEBHOOK_SECRET,
} = process.env;

export { 
  PORT, 
  NODE_ENV, 
  MONGO_URI, 
  SENTRY_DSN,
  DATABASE_URL,
  CLERK_PUBLISHABLE_KEY,
  CLERK_SECRET_KEY,
  CLIENT_URL,
  RESEND_API_KEY,
  RESEND_FROM_EMAIL,
  R2_ACCOUNT_ID,
  R2_ACCESS_KEY_ID,
  R2_SECRET_ACCESS_KEY,
  R2_BUCKET_NAME,
  R2_PUBLIC_URL,
  PAYMENT_WEBHOOK_SECRET,
};
